### ISSUE TITLE
When specifying apt key in full, fails with yaml error

### ISSUE THREAD

**Issue by xavpaice** [juju/charm-helpers#336]
When I set a charm's install_keys to the full ascii encoded key (see https://github.com/juju/charm-helpers/issues/304 for the reason I'm doing this), I get an error:

```
2019-06-17 05:19:34 ERROR juju-log Hook error:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-telegraf-276/.venv/lib/python3.5/site-packages/charms/reactive/__init__.py", line 72, in main
    hookenv._run_atstart()
  File "/var/lib/juju/agents/unit-telegraf-276/.venv/lib/python3.5/site-packages/charmhelpers/core/hookenv.py", line 1211, in _run_atstart
    callback(*args, **kwargs)
  File "/var/lib/juju/agents/unit-telegraf-276/charm/reactive/apt.py", line 117, in configure_sources
    keys_var='install_keys')
  File "/var/lib/juju/agents/unit-telegraf-276/.venv/lib/python3.5/site-packages/charmhelpers/fetch/__init__.py", line 130, in configure_sources
    keys = safe_load((config(keys_var) or '').strip()) or None
  File "/var/lib/juju/agents/unit-telegraf-276/.venv/lib/python3.5/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/var/lib/juju/agents/unit-telegraf-276/.venv/lib/python3.5/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/var/lib/juju/agents/unit-telegraf-276/.venv/lib/python3.5/site-packages/yaml/constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "/var/lib/juju/agents/unit-telegraf-276/.venv/lib/python3.5/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/var/lib/juju/agents/unit-telegraf-276/.venv/lib/python3.5/site-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/var/lib/juju/agents/unit-telegraf-276/.venv/lib/python3.5/site-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/var/lib/juju/agents/unit-telegraf-276/.venv/lib/python3.5/site-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/var/lib/juju/agents/unit-telegraf-276/.venv/lib/python3.5/site-packages/yaml/scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "/var/lib/juju/agents/unit-telegraf-276/.venv/lib/python3.5/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/var/lib/juju/agents/unit-telegraf-276/.venv/lib/python3.5/site-packages/yaml/scanner.py", line 579, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 2, column 8:
    Version: SKS 1.1.6
           ^
```

**Comment by dshcherb** [comment]
@xavpaice 

install_keys is not exactly straightforward to use as this is a list of multi-line strings. Do you have install_keys formatted as follows?

```
  telegraf:
    charm: cs:telegraf
    options:
      install_sources: |
        - 'deb http://ppa.launchpad.net/telegraf-devs/ppa/ubuntu bionic main'
      install_keys: |-
        - |
          -----BEGIN PGP PUBLIC KEY BLOCK-----
          Version: SKS 1.1.6
          Comment: Hostname: keyserver.ubuntu.com

          mQINBFcVSuIBEAC80aj0tAQ6+NhGV/bkSwu6Oj+BpDR50Be3uBv7ttdtvChL5zHTnaxjdK3h
          LKSyrDLlmSOkffQ2uO7CxvqeF09MsHhyvrDDx0EY54//xxoAB++PoB2OQqmqldg3Al5Hp4Dz
          rllV5CIX5PD8NGX8UpO3HXk5wEwn9G81l8cia3vPveU82EIkHMiJGpk6+L86OMlwXzxkSI3M
          xXgNFKQc+ELDYLvGSseYC9vPN3kdmFoo/UjznPPE4fxr4bXit3N8Abl1jYjBa0x6SWkK1BAb
          s8w3BXtvyk90z9Oyme69wPD4zAYfFp+kN2nDmTDBMtNCyMu9oatdI5SukMNK4Lcm8eAE6VNs
          04j7BKvGk9+17M8WP9Pw8nIisOwScS9gUlJlLUpnBaJ+sxoOvGQ4mzZxYMKzJh0E58aEX3bS
          AyzQfsae8bZLNOTcgotyzzIDJFF9npzu3wmKjeOt/706p4LiDqKUbQK6cI+QcJ/y80ZUK8pB
          M043ttSHWLmTBFX2drp6zQGae9+02fX89ZD+5c+MPlubJMYCCKkvQT4OssHfC+dVDQ66rwUy
          OObrzsVgikdpIxQVitL3J+Dms56xAkdFfoo+qdxxdv9S/eakc5mfavc/4WVvmFDaJiqJnJRR
          Ryw1zApRtuweEEdVn8niy1mahoKpWaw1pTI4AazjWI6xJH1JyQARAQABtB9MYXVuY2hwYWQg
          UFBBIGZvciBUZWxlZ3JhZiBEZXZziQI4BBMBAgAiBQJXFUriAhsDBgsJCAcDAgYVCAIJCgsE
          FgIDAQIeAQIXgAAKCRDxDL4ByUQG9UgbEACa4IzdeYxH/S5I6MrZfvWNo/JTZ/MZWDD+QlMW
          60ThAemCUSE+NJvZZ1q7ovGFpYnHJT9GQXOwJAX1quDUqyM1uXNmLlOyIVNnmjUTINoLhw2V
          iC8E7dMWC9w4Na2fKezmNHH00kNl43ncstIjjZ3pLnDGYm1y0ItiCUcTRgHhx2cUZ/vStz1S
          Pdqj4P3i8vuspoYJ2T3VPlM/0G+u9Yjuy3Uzu9RugOyO3UJPoi3+4O2VTNosSBy5MILVCp49
          eigyFVGpq5sT/c86qd1zqmsNWEubrlzDfETS4LMj9epr46ZKPXGQkeryt1m2Oe0HkIdNZ+IQ
          5p+i9fnEy7/1uKTXWQYsg2UWsLA2PvTvwY8JxxMhUFgv12q2w7STntqJyi9PLItYNtbtKoS3
          XZCCMqQLCWMXHY+2ol6rRSfs06H/wzlR8LjDaEXkDVuDmqMtcbgTboZYblsGxst7I/Y4Wgfi
          J52uiIyobQ69uJbG0XeRTLZ3WyrBkopEsTX/+sQjVqbADXYU4hBVDgnCf2uN/5dcwSEvDj8/
          +WsToAfEJkscRBsQjTLVzf+eFqHLrbqz/yoYIqBc//IJMBSbxIf5mrOHHLdbOuMCB6PVwpTI
          vLFOSDNPuVDX+S1goA8KJTnXpm8jWDynn3XaXx3AlYw4iZ0ETSgQLQLRd6JuPOEGXsGdBA==
          =ufaX
          -----END PGP PUBLIC KEY BLOCK-----
```

**Comment by xavpaice** [comment]
Thanks for that - it was the formatting.
