### ISSUE TITLE
ubuntu_apt_pkg is not yet a faithful simulation of apt_pkg

### ISSUE THREAD

**Issue by ajkavanagh** [juju/charm-helpers#378]
It seems to be missing the property: `current_ver` on one of the objects.  See this bug: https://bugs.launchpad.net/charm-ceph-radosgw/+bug/1846227 for more details.

```
unit_tests.test_ceph.CephRadosGWCephTests.test_setup_ipv6_not_install_backports
-------------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    b'Traceback (most recent call last):'
    b' File "/home/chris/code/canonical/charms/charm-ceph-radosgw/.tox/py37/lib/python3.7/site-packages/mock/mock.py", line 1330, in patched'
    b' return func(*args, **keywargs)'
    b' File "/home/chris/code/canonical/charms/charm-ceph-radosgw/unit_tests/test_ceph.py", line 172, in test_setup_ipv6_not_install_backports'
    b' utils.setup_ipv6()'
    b' File "hooks/utils.py", line 235, in setup_ipv6'
    b" vc = apt_pkg.version_compare(get_pkg_version('haproxy'), '1.5.3')"
    b' File "hooks/utils.py", line 321, in get_pkg_version'
    b' version = apt_pkg.upstream_version(pkg.current_ver.ver_str)'
    b"AttributeError: 'NoneType' object has no attribute 'ver_str'"
```

**Comment by fnordahl** [comment]
Actually, I think it is a matter of a unit test mock becoming out of date in the consuming code [0], caused by the new location of the apt simulation.

The existing mocking hid a bug in the code as the same sequence produce the same results with the actual ``apt_pkg`` module.

Example:
```
import apt

apt.apt_pkg.init()
apt.apt_pkg.config.set("Dir::Cache::pkgcache", "")
apt.apt_pkg.config.set("Dir::Cache::srcpkgcache", "")
cache = apt.apt_pkg.Cache()
pkg = cache['haproxy']
print(apt.apt_pkg.upstream_version(pkg.current_ver.ver_str))
```

Output:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Traceback (most recent call last):
  File "example.py", line 8, in <module>
    print(apt.apt_pkg.upstream_version(pkg.current_ver.ver_str))
AttributeError: 'NoneType' object has no attribute 'ver_str'
```

0: https://github.com/openstack/charm-ceph-radosgw/blob/71b3e3b8eb1fe6a2073999ea518c8fc364303741/unit_tests/test_ceph.py#L150
