### ISSUE TITLE
contrib/network/ovs: SimpleOVSDB de-serialization issue

### ISSUE THREAD

**Issue by fnordahl** [juju/charm-helpers#510]
Got this Traceback while attempting to find bridge for port:
```
2020-09-10 07:23:33 ERROR juju-log Action "cleanup" failed: "argument of type 'UUID' is not iterable" "Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-neutron-openvswitch-1/charm/actions/cleanup", line 159, in main
    action(args)
  File "/var/lib/juju/agents/unit-neutron-openvswitch-1/charm/actions/cleanup", line 128, in cleanup
    remove_patch_ports('br-int')
  File "/var/lib/juju/agents/unit-neutron-openvswitch-1/charm/actions/cleanup", line 61, in remove_patch_ports
    for patch in list(ch_ovs.patch_ports_on_bridge(bridge)):
  File "hooks/charmhelpers/contrib/network/ovs/__init__.py", line 645, in patch_ports_on_bridge
    if bridge_for_port(port['_uuid']) == bridge:
  File "hooks/charmhelpers/contrib/network/ovs/__init__.py", line 621, in bridge_for_port
    if port_uuid in bridge['ports']:
TypeError: argument of type 'UUID' is not iterable
```

With a bridge config like this:
```
# ovs-vsctl list bridge
_uuid               : e5e4efe8-131a-4da9-bb17-837a0cb55260
auto_attach         : []
controller          : []
datapath_id         : "0000eaefe4e5a94d"
datapath_type       : system
datapath_version    : "<unknown>"
external_ids        : {}
fail_mode           : []
flood_vlans         : []
flow_tables         : {}
ipfix               : []
mcast_snooping_enable: false
mirrors             : []
name                : br-ex
netflow             : []
other_config        : {}
ports               : [d45de15f-a522-4159-934c-8ba4f5dd1c21]
protocols           : []
rstp_enable         : false
rstp_status         : {}
sflow               : []
status              : {}
stp_enable          : false

_uuid               : 76b1cbce-2866-4789-9121-f69518f7c203
auto_attach         : []
controller          : [497f152b-62f6-4102-9af5-90f99bf2fc60]
datapath_id         : "0000cecbb1768947"
datapath_type       : system
datapath_version    : "<unknown>"
external_ids        : {}
fail_mode           : secure
flood_vlans         : []
flow_tables         : {}
ipfix               : []
mcast_snooping_enable: false
mirrors             : []
name                : br-tun
netflow             : []
other_config        : {mac-table-size="50000"}
ports               : [2230e03d-8924-4b6d-a973-4d1aec500c23, 981b7b19-7042-4999-9edf-d0ce91025be6, aeccfc26-e97a-4d06-9344-eeb4af3baa97, d73b1a8d-f916-496d-a662-ff8b13cccac6]
protocols           : [OpenFlow10, OpenFlow13, OpenFlow14]
rstp_enable         : false
rstp_status         : {}
sflow               : []
status              : {}
stp_enable          : false

_uuid               : 36a77016-3fc2-4721-9466-feb6e317281f
auto_attach         : []
controller          : [a5dae629-d489-43aa-b81a-8245b7a27703]
datapath_id         : "00001670a7362147"
datapath_type       : system
datapath_version    : "<unknown>"
external_ids        : {}
fail_mode           : secure
flood_vlans         : []
flow_tables         : {}
ipfix               : []
mcast_snooping_enable: false
mirrors             : []
name                : br-int
netflow             : []
other_config        : {mac-table-size="50000", mcast-snooping-disable-flood-unregistered=False}
ports               : [27debf07-0952-495b-8b3a-fcd2d367e891, c42652a3-242d-4581-9df0-0392785bb71c, d8d45d71-05b6-4348-9ab3-18429deb7755, efd8e3d0-1a5a-4717-814a-9dba29b6b807]
protocols           : [OpenFlow10, OpenFlow11, OpenFlow12, OpenFlow13, OpenFlow14]
rstp_enable         : false
rstp_status         : {}
sflow               : []
status              : {}
stp_enable          : false

_uuid               : 2b25e29a-0ebe-411c-a837-d6d152a22c45
auto_attach         : []
controller          : [22e94228-cf46-422d-9f30-afa34549aa10]
datapath_id         : "00009ae2252b1c41"
datapath_type       : system
datapath_version    : "<unknown>"
external_ids        : {}
fail_mode           : secure
flood_vlans         : []
flow_tables         : {}
ipfix               : []
mcast_snooping_enable: false
mirrors             : []
name                : br-data
netflow             : []
other_config        : {mac-table-size="50000"}
ports               : [601cbf8e-506e-4bd0-9bbb-f4ebe64a4171, ad9ba534-416d-4fa4-b95e-ece0a6eddc60]
protocols           : [OpenFlow10, OpenFlow13, OpenFlow14]
rstp_enable         : false
rstp_status         : {}
sflow               : []
status              : {}
stp_enable          : false
```

**Comment by fnordahl** [comment]
Gah, looks like this is just how `ovs-vsctl` behaves:

Bridge with one protocol:
```
{'data': [[['uuid', '9b0d7cd5-1c18-440c-af9f-f72e2a266225'],
           ['set', []],
           ['set', []],
           '0000d67c0d9b0c44',
           '',
           '<unknown>',
           ['map', []],
           ['set', []],
           ['set', []],
           ['map', []],
           ['set', []],
           False,
           ['set', []],
           'testbr',
           ['set', []],
           ['map', []],
           ['uuid', 'ee065ac5-48dc-41f3-a421-b4ad7a0aa1c8'],
           'OpenFlow10',
           False,
           ['map', []],
           ['set', []],
           ['map', []],
           False]],
 'headings': ['_uuid',
              'auto_attach',
              'controller',
              'datapath_id',
              'datapath_type',
              'datapath_version',
              'external_ids',
              'fail_mode',
              'flood_vlans',
              'flow_tables',
              'ipfix',
              'mcast_snooping_enable',
              'mirrors',
              'name',
              'netflow',
              'other_config',
              'ports',
              'protocols',
              'rstp_enable',
              'rstp_status',
              'sflow',
              'status',
              'stp_enable']}
```
Bridge with multiple protocols:
```
{'data': [[['uuid', '9b0d7cd5-1c18-440c-af9f-f72e2a266225'],
           ['set', []],
           ['set', []],
           '0000d67c0d9b0c44',
           '',
           '<unknown>',
           ['map', []],
           ['set', []],
           ['set', []],
           ['map', []],
           ['set', []],
           False,
           ['set', []],
           'testbr',
           ['set', []],
           ['map', []],
           ['uuid', 'ee065ac5-48dc-41f3-a421-b4ad7a0aa1c8'],
           ['set', ['OpenFlow10', 'OpenFlow12']],
           False,
           ['map', []],
           ['set', []],
           ['map', []],
           False]],
 'headings': ['_uuid',
              'auto_attach',
              'controller',
              'datapath_id',
              'datapath_type',
              'datapath_version',
              'external_ids',
              'fail_mode',
              'flood_vlans',
              'flow_tables',
              'ipfix',
              'mcast_snooping_enable',
              'mirrors',
              'name',
              'netflow',
              'other_config',
              'ports',
              'protocols',
              'rstp_enable',
              'rstp_status',
              'sflow',
              'status',
              'stp_enable']}
```

**Comment by fnordahl** [comment]
I guess the only alternative would be to load the schema to know how to represent each field, but I think that would bring us out of scope of "Simple".

Perhaps the only alternative is to document the behavior.
